apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  labels:
    open-cluster-management.io/policy-set: additional-hub-policies
  name: additional-hub-policies
  namespace: policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-openshift-plus-hub
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: PolicySet
  name: additional-hub-policies